# Generated by Django 5.1.6 on 2025-03-29 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashcardGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="flashcards.flashcardgroup"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScorePerFlashcard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField(default=0)),
                (
                    "flashcard",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="flashcards.flashcard"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="flashcards.user")),
            ],
        ),
    ]
