# Generated by Django 5.1.6 on 2025-03-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreperflashcard",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name="flashcardgroup",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="flashcards", to="flashcards.flashcardgroup"
            ),
        ),
        migrations.AlterField(
            model_name="scoreperflashcard",
            name="flashcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="scores", to="flashcards.flashcard"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
